import Head from 'next/head';
import Image from 'next/image';
import { Track, Time } from 'types';
import useSWR from 'swr';
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react';
import Login from '@/components/Login';
import Link from 'next/link';

const fetcher = (url: string) => fetch(url).then((res) => res.json());

let user_uuid: string | undefined;

function submitTime(e: any) {
  e.preventDefault();
  const data = new FormData(e.target);
  let value = Object.fromEntries(data.entries());

  fetch('/api/times', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      user_id: user_uuid,
      track: value.track,
      time: value.time,
    }),
  });
}

export default function Home() {
  const session = useSession();
  const supabase = useSupabaseClient();

  const { data: tracks, error: tracksError } = useSWR<Track[]>(
    '/api/track',
    fetcher
  );

  if (tracksError) return <div>failed to load</div>;
  if (!tracks) return <div>loading...</div>;

  console.log(session);

  user_uuid = session?.user.id;

  return (
    <>
      <Head>
        <title>Raceboards</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/helmet.png" />
      </Head>
      {session?.user.aud !== 'authenticated' ? (
        <Login />
      ) : (
        <>
          <header className="grid h-20 grid-cols-3 bg-[#3D3D3D]">
            <Link
              className="place-self-center justify-self-start pl-5 text-xl"
              href={'/times'}
            >
              Times
            </Link>
            <div className="col-start-2 flex items-center gap-5 place-self-center">
              <h1 className="text-3xl font-light text-white">
                Willkommen zu Raceboards,{' '}
                {session?.user.user_metadata.full_name}
              </h1>
              <Image
                src={session.user.user_metadata.avatar_url}
                className="rounded-full"
                alt="avatar"
                width={50}
                height={50}
              />
            </div>
            <button
              className="place-self-center justify-self-end pr-5"
              onClick={() => supabase.auth.signOut()}
            >
              <Image src="/logout.svg" width={20} height={20} alt="logout" />
            </button>
          </header>
          <main>
            <div className="flex h-[calc(100vh-5rem)]  items-center justify-center bg-gray-800">
              <div className="w-1/3 rounded-lg border border-gray-600 bg-gray-600 p-2  shadow-xl">
                <form
                  method="POST"
                  action="localhost:3000/api/times"
                  onSubmit={submitTime}
                >
                  <div>
                    <label
                      className="mb-2 block text-sm font-medium text-white"
                      htmlFor="track"
                    >
                      Track
                    </label>
                    <select
                      className=" block w-full rounded-lg border border-gray-600 bg-gray-700 p-2.5 text-sm text-white placeholder-gray-400 focus:border-blue-500  focus:ring-blue-500 "
                      name="track"
                      id="track"
                    >
                      {tracks?.map((track) => (
                        <option key={track.id} value={track.name}>
                          {track.name}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div>
                    <label
                      className="mb-2 block text-sm font-medium text-white"
                      htmlFor="time"
                    >
                      Time
                    </label>
                    <input
                      className='"bg-gray-50 block w-full rounded-lg border border-gray-600 bg-gray-700 p-2.5 text-sm text-white placeholder-gray-400 focus:border-blue-500 focus:ring-blue-500 '
                      type="text"
                      name="time"
                      id="time"
                      required
                    />
                  </div>

                  <div>
                    <button
                      className="mt-3 w-full  rounded-lg bg-blue-600 px-5 py-2.5 text-center text-sm font-medium text-white hover:bg-blue-700 focus:outline-none focus:ring-4 focus:ring-blue-800 sm:w-auto "
                      type="submit"
                    >
                      Submit
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </main>
        </>
      )}
    </>
  );
}
