import Head from 'next/head';
import Image from 'next/image';
import { Track, Time } from 'types';
import useSWR from 'swr';
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react';
import Login from '@/components/Login';
import Link from 'next/link';

const fetcher = (url: string) => fetch(url).then((res) => res.json());

let user_uuid: string | undefined;

function submitTime(e: any) {
  e.preventDefault();
  const data = new FormData(e.target);
  let value = Object.fromEntries(data.entries());

  fetch('/api/times', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      user_id: user_uuid,
      track: value.track,
      time: value.time,
    }),
  });
}

export default function Home() {
  const session = useSession();
  const supabase = useSupabaseClient();

  const { data: tracks, error: tracksError } = useSWR<Track[]>(
    '/api/track',
    fetcher
  );

  if (tracksError) return <div>failed to load</div>;
  if (!tracks) return <div>loading...</div>;

  user_uuid = session?.user.id;

  return (
    <>
      <Head>
        <title>Raceboards</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/helmet.png" />
      </Head>
      {session?.user.aud !== 'authenticated' ? (
        <Login />
      ) : (
        <>
          <header className="h-20 grid grid-cols-3 bg-blue-200">
            <Link
              className="place-self-center justify-self-start pl-5 text-xl"
              href={'/times'}
            >
              Times
            </Link>
            <h1 className="text-3xl font-light col-start-2 place-self-center">
              Willkommen zu Raceboards, {session?.user.user_metadata.full_name}
            </h1>
            <button
              className="place-self-center justify-self-end pr-5"
              onClick={() => supabase.auth.signOut()}
            >
              <Image src="/logout.svg" width={20} height={20} alt="logout" />
            </button>
          </header>
          <main>
            <div className="bg-gray-200 dark:bg-gray-800 h-[calc(100vh-5rem)]  flex justify-center items-center">
              <div className="w-1/3 border border-gray-600 rounded-lg shadow-xl bg-gray-300 dark:bg-gray-600  p-2">
                <form
                  method="POST"
                  action="localhost:3000/api/times"
                  onSubmit={submitTime}
                >
                  <div>
                    <label
                      className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                      htmlFor="track"
                    >
                      Track
                    </label>
                    <select
                      className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                      name="track"
                      id="track"
                    >
                      {tracks?.map((track) => (
                        <option key={track.id} value={track.name}>
                          {track.name}
                        </option>
                      ))}
                    </select>
                  </div>

                  <div>
                    <label
                      className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                      htmlFor="time"
                    >
                      Time
                    </label>
                    <input
                      className='"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'
                      type="text"
                      name="time"
                      id="time"
                      required
                    />
                  </div>

                  <div>
                    <button
                      className="bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium text-sm w-full sm:w-auto mt-3 px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 rounded-lg text-white "
                      type="submit"
                    >
                      Submit
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </main>
        </>
      )}
    </>
  );
}
